reference_tokenizer_hf_name: meta-llama/Llama-2-7b-hf
reference_tokenizer_chunk_size: 256
num_proc: 16
subsample_ratio: 0.05
hf_name: allenai/dolma
subset: v1_6-sample
split: train
text_column: text
id_column: id
domain_column: source
metadata_column: null
pages_per_domain: 5
enforce_pages_per_domain: true
look_in_metadata_for_domain: false
look_in_metadata_for_id: false
output_name: chunked_dolma_sample
