chunked_pretraining_data_sample: chunked_redpajama_v2
raw_job_output_dir: raw_job_outputs
evals:
  - eleuther_name: arc_easy
    metric: acc,none
    lower_is_better: false
  - eleuther_name: piqa
    metric: acc,none
    lower_is_better: false
  - eleuther_name: sciq
    metric: acc,none
    lower_is_better: false
  - eleuther_name: lambada
    metric: perplexity,none
    lower_is_better: true
  - eleuther_name: lambada_openai_mt_de
    metric: perplexity,none
    lower_is_better: true
  - eleuther_name: lambada_openai_mt_es
    metric: perplexity,none
    lower_is_better: true
  - eleuther_name: lambada_openai_mt_fr
    metric: perplexity,none
    lower_is_better: true
  - eleuther_name: lambada_openai_mt_it
    metric: perplexity,none
    lower_is_better: true
llms:
  - family: bloom
    hf_names:
      - bigscience/bloom-560m
      - bigscience/bloom-1b1
      - bigscience/bloom-3b	
      - bigscience/bloom-7b1
  - family: starcoder
    hf_names:
      - bigcode/starcoderbase-1b
      - bigcode/starcoderbase-3b
      - bigcode/starcoderbase-7b
      - bigcode/starcoder2-7b
      - bigcode/starcoder2-3b
  - family: cerebras
    hf_names:
      - cerebras/Cerebras-GPT-111M
      - cerebras/Cerebras-GPT-256M
      - cerebras/Cerebras-GPT-590M
      - cerebras/Cerebras-GPT-1.3B
      - cerebras/Cerebras-GPT-2.7B
      - cerebras/Cerebras-GPT-6.7B
      - cerebras/btlm-3b-8k-base
  - family: gpt2
    hf_names:
      - gpt2
      - gpt2-medium
      - gpt2-large
      - gpt2-xl
  - family: gpt-j
    hf_names:
      - EleutherAI/gpt-j-6b
  - family: pythia
    hf_names:
      - EleutherAI/pythia-31m
      - EleutherAI/pythia-70m
      - EleutherAI/pythia-160m
      - EleutherAI/pythia-410m
      - EleutherAI/pythia-1b
      - EleutherAI/pythia-1.4b
      - EleutherAI/pythia-2.8b
      - EleutherAI/pythia-6.9b
  - family: gpt-neo
    hf_names:
      - EleutherAI/gpt-neo-125m	
      - EleutherAI/gpt-neo-1.3B	
      - EleutherAI/gpt-neo-2.7B	
  - family: danube
    hf_names:
      - h2oai/h2o-danube-1.8b-base
      - h2oai/h2o-danube2-1.8b-base
      - h2oai/h2o-danube3-500m-base
      - h2oai/h2o-danube3-4b-base
  - family: falcon
    hf_names:
      - tiiuae/falcon-7b
      - tiiuae/falcon-rw-1b
  - family: smollm
    hf_names:
      - HuggingFaceTB/SmolLM-135M
      - HuggingFaceTB/SmolLM-360M
      - HuggingFaceTB/SmolLM-1.7B
  - family: yi
    hf_names:
      - 01-ai/Yi-6B
  - family: mistral
    hf_names:
      - mistralai/Mistral-7B-v0.1
  - family: qwen
    hf_names:
      - Qwen/Qwen-1_8B
      - Qwen/Qwen-7B
      - Qwen/Qwen1.5-0.5B
      - Qwen/Qwen1.5-1.8B
      - Qwen/Qwen1.5-4B
      - Qwen/Qwen1.5-7B
      - Qwen/Qwen2-0.5B
      - Qwen/Qwen2-1.5B
      - Qwen/Qwen2-7B
  - family: phi
    hf_names:
      - microsoft/phi-1_5
      - microsoft/phi-2
  - family: gemma
    hf_names:
      - google/gemma-2b
      - google/gemma-7b
      - google/gemma-2-2b
  - family: opt
    hf_names:
      - facebook/opt-125m
      - facebook/opt-350m
      - facebook/opt-1.3b
      - facebook/opt-2.7b
      - facebook/opt-6.7b
  - family: xglm
    hf_names:
      - facebook/xglm-1.7B
      - facebook/xglm-4.5B
  - family: codellama
    hf_names:
      - codellama/CodeLlama-7b-hf
  - family: deepseek
    hf_names:
      - deepseek-ai/deepseek-llm-7b-base
  - family: deepseek-coder
    hf_names:
      - deepseek-ai/deepseek-coder-1.3b-base
      - deepseek-ai/deepseek-coder-6.7b-base
  - family: mpt
    hf_names:
      - mosaicml/mpt-7b 
  - family: llama
    hf_names:
      - meta-llama/Llama-2-7b-hf
      - meta-llama/Meta-Llama-3-8B
      - meta-llama/Meta-Llama-3.1-8B
      - huggyllama/llama-7b
  - family: olmo
    hf_names:
      - allenai/OLMo-1B-hf
      - allenai/OLMo-7B-hf
      - allenai/OLMo-7B-0424-hf
  - family: open-llama
    hf_names:
      - openlm-research/open_llama_3b
      - openlm-research/open_llama_7b
      - openlm-research/open_llama_3b_v2
      - openlm-research/open_llama_7b_v2
  - family: internlm
    hf_names:
      - internlm/internlm2-7b
  - family: decilm
    hf_names:
      - Deci/DeciLM-7B
  - family: stablelm
    hf_names:
      - stabilityai/stablelm-base-alpha-3b
      - stabilityai/stablelm-base-alpha-7b-v2
      - stabilityai/stablelm-base-alpha-7b
      - stabilityai/stablelm-2-1_6b
  - family: rpj-incite
    hf_names:
      - togethercomputer/RedPajama-INCITE-Base-3B-v1	
      - togethercomputer/RedPajama-INCITE-Base-7B-v0.1	
  - family: amber
    hf_names:
      - LLM360/Amber
  - family: tinyllama
    hf_names:
      - TinyLlama/TinyLlama_v1.1
  - family: mpt-redpajama
    hf_names:
      - mosaicml/mpt-1b-redpajama-200b
