reference_tokenizer_hf_name: meta-llama/Llama-2-7b-hf
reference_tokenizer_chunk_size: 256
num_proc: 16
subsample_ratio: 1  # If this is 0 < n < 1, it only uses the first n*100% of the data
hf_name: togethercomputer/RedPajama-Data-V2
subset: sample
split: train
text_column: raw_content
id_column: url
domain_column: source_domain
metadata_column: meta
pages_per_domain: 25
enforce_pages_per_domain: true
look_in_metadata_for_domain: true
look_in_metadata_for_id: true
output_name: chunked_datasets/chunked_rpjv2_sample_256
