bpb_csv: ../get_error_and_bpb/bpb_csvs/chunked_rpjv2_sample_bpb_domain.csv
error_csv: ../get_error_and_bpb/error_csvs/error.csv
target_benchmark_groups:
  - name: sciq
    benchmarks:
      - sciq
  - name: piqa
    benchmarks:
      - piqa
  - name: arc_easy
    benchmarks:
      - arc_easy
  - name: lambada
    benchmarks:
      - lambada_openai
      - lambada_standard
  - name: lambada_fr
    benchmarks:
      - lambada_openai_mt_fr
  - name: lambada_de
    benchmarks:
      - lambada_openai_mt_de
  - name: lambada_it
    benchmarks:
      - lambada_openai_mt_it
  - name: lambada_es
    benchmarks:
      - lambada_openai_mt_es 
hf_tokenizer_name: EleutherAI/pythia-160m
desired_filter_ratio: 0.1  # Lower means more filtering
num_proc: 16
fasttext_label_aggregation: id
estimator: spearmanr
chunked_pretraining_data_sample: ../get_error_and_bpb/chunked_datasets/chunked_rpjv2_sample
